### GET request to example server
POST http://localhost:3000/markets
Content-Type: application/json

{
  "question": "BTC higher than 60k",
  "price": 52,
  "status": "unresolved"
}
###

###
GET http://localhost:3000/markets/3
Accept: application/json
###

###
PATCH http://localhost:3000/markets/3
Content-Type: application/json

{
  "status": "resolved"
}
###

###
GET http://localhost:3000/markets/3
Accept: application/json
###

###
DELETE http://localhost:3000/markets/3
###

###
GET http://localhost:3000/markets/3
Accept: application/json
###